language: node_js
sudo: false
env: CI=true
node_js:
- iojs
script: "npm run verify"
#after_success:
#- bin/build.sh
notifications:
  email:
  - ogataken@gmail.com
deploy:
  provider: releases
  api_key:
    secure: "GfspJV8+cSBJERtTfXiwbyM5WTRD95hfbAdkZLHuaIqh/Q7/lO7L5FXqucwIwRt++Rz6kG624x+pkjRa6+HJbnzunLW03s/wj1eu/ts3o0Md6I4euaGxqCYzzwd0KcM4YJiGpRYtQFqWqEfdrafTXipZziylKDbXK6O0/ynJiqo="
  file:
  - "build/close-your-issues-win32.zip"
  - "build/close-your-issues-win64.zip"
  - "build/close-your-issues-osx32.zip"
  - "build/close-your-issues-osx64.zip"
  - "build/close-your-issues-linux32.zip"
  - "build/close-your-issues-linux64.zip"
  on:
    repo: lyrictenor/nwjs-close-your-issues
    tags: true
  skip_cleanup: true
