language: node_js
sudo: false
env: CI=true
node_js:
- iojs
script: "npm run verify"
after_success:
- bin/build.sh
notifications:
  email:
  - ogataken@gmail.com
deploy:
  provider: releases
  api_key:
    secure: B0D1fd0tfkBSLV56MiS3WzrmRocdoluJYbVKKnTUv8naxtRd5WNtRHpe5Uok8yUxnTO+ARzaMmvOcaQS3B41+Y/EC3bv1xeWuwHifJRghBEn6uz5XQEWMlD/LIh/zi+KfV3rqZGSHPo9kIvTLdrVH8JWQ61FHJmBS20ObZdqPdo=
  file:
  - "../clean-env/build/close-your-issues-win32.zip"
  - "../clean-env/build/close-your-issues-win64.zip"
  - "../clean-env/build/close-your-issues-osx32.zip"
  - "../clean-env/build/close-your-issues-osx64.zip"
  - "../clean-env/build/close-your-issues-linux32.zip"
  - "../clean-env/build/close-your-issues-linux64.zip"
  on:
    repo: sanemat/nwjs-close-your-issues
    tags: true
  skip_cleanup: true
