language: node_js
sudo: false
env: CI=true
node_js:
- iojs
script: "npm run verify"
cache:
  directories:
    - node_modules
after_success:
- bin/build.sh
notifications:
  email:
  - ogataken@gmail.com
deploy:
  provider: releases
  file:
  - "build/close-your-issues-win32.zip"
  - "build/close-your-issues-win64.zip"
  - "build/close-your-issues-osx32.zip"
  - "build/close-your-issues-osx64.zip"
  - "build/close-your-issues-linux32.zip"
  - "build/close-your-issues-linux64.zip"
  on:
    repo: lyrictenor/nwjs-close-your-issues
    tags: true
  skip_cleanup: true
